"""add avatar path and usertype to User

Revision ID: f42eb52a2a2b
Revises: 28c0a3737b7e
Create Date: 2024-10-19 14:55:32.736881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42eb52a2a2b'
down_revision: Union[str, None] = '28c0a3737b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_path', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.Enum('google', 'default', name='usertype'), nullable=True))
    op.create_unique_constraint(None, 'users', ['avatar_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'avatar_path')
    # ### end Alembic commands ###
